### ISSUE TITLE
Graph hasn't updated since 2020-11-23

### ISSUE THREAD

**Issue by rmzelle** [cpina/csls-styles-report#4]
Screenshot from just now at https://pinux.info/csls_counter/:

![image](https://user-images.githubusercontent.com/77951/107532800-44df2400-6b8c-11eb-82ea-57f904dff0e0.png)

Mousing all the way to right suggests the graph hasn't updated since 2020-11-23. Pretty sure the "Number of styles" at the bottom of the page are outdated too.

**Comment by rmzelle** [comment]
https://www.zotero.org/styles also reports 9980 styles. Just keeping an eye on when we hit 10,000!

**Comment by rmzelle** [comment]
Ah, I assume this is because our migration from Travis CI to GitHub Actions on that date: https://github.com/citation-style-language/styles/pull/5111

**Comment by cpina** [comment]
I'm happy to know that this is being used! :-)

I've just had a quick look and https://pinux.info/csls_counter data is from the styles from https://github.com/citation-style-language/styles-distribution repo and the last commit is in November. Is this intended? for the styles-counter I'm happy to change it to https://github.com/citation-style-language/styles . Let me know and I'll change...

PS: I wonder if any reference manager (e.g. Mendeley) is missing updates because of this. If I remember correctly when I left (in 2019) it might have been using styles-distribution? I had a quick look in Mendeley and I think that it doesn't have the updates after November (just looked a few styles updated after november in the /styles repo).

**Comment by rmzelle** [comment]
We deprecated https://github.com/citation-style-language/styles-distribution in favor of having version branches in the main repo (i.e., https://github.com/citation-style-language/styles/tree/v1.0.1 right now). Sorry, that hasn't been clearly communicated.

**Comment by cpina** [comment]
Not a problem - I was just going to say that it makes 100% sense to deprecate https://github.com/citation-style-language/styles-distribution : now it's easier to validate styles during the PR before merging them into master. I think that styles-distribution was before times where this was possible easily. I'll change now the script.

**Comment by rmzelle** [comment]
> I was just going to say that it makes 100% sense to deprecate https://github.com/citation-style-language/styles-distribution

Yeah, we should probably archive that repo with a clear message to migrate. (there is some related discussion at https://github.com/citation-style-language/styles/pull/5165#issuecomment-743485742; the whole conversation was a bit scattered across issues/PRs)

**Comment by cpina** [comment]
https://pinux.info/csls_counter fixed, at some point I might improve that a bit... :-)

**Comment by rmzelle** [comment]
Thanks!

**Comment by cpina** [comment]
> https://www.zotero.org/styles also reports 9980 styles. Just keeping an eye on when we hit 10,000!

Congratulations, 10,004! :-)
